### ISSUE TITLE
Run the Deep Hedging Algorithm (Simple Network) model.fit无label

### ISSUE THREAD

**Issue by qiquanbuaa** [YuMan-Tam/deep-hedging-demo#2]
同学您好，十分感谢您follow <Deep Hedging>的Git项目，对我帮助很大。我在执行您的Git项目时，有一处问题不太理解，请您耐心指教。
执行Run the Deep Hedging Algorithm (Simple Network)时，
model_simple.fit(x=xtrain, batch_size=batch_size, epochs=epochs,           validation_data=xtest, verbose=1)
输入变量为什么只有x，而没有label。
当我将其更改(xtrain, S_train, ..., xtest, S_test)时，
报错如下：
 ValueError: ('Error when checking model target: expected no data, but got:',
如果您有时间的话，请您指导。
有可能的话，也可以邮件联系，zhangzian@buaa.edu.cn
感谢您的帮助！

**Comment by YuMan-Tam** [comment]
The variable ```xtrain``` is a ```list``` of input tensors that already include ```S_train```. In particular:

```
# Structure of xtrain:
#   1) Trade set: [S]
#   2) Information set: [S] (or the normalized variant)
#   3) payoff (dim = 1)
```
Hence, the model does not expect to receive ```S_train``` again after ```xtrain```.  Same for the validation data. ```xtest``` is already included in the argument ```validation_data```, so it's not expected in the argument ```x```.

**Comment by qiquanbuaa** [comment]
Got it! Thanks a lot for your help.
