### ISSUE TITLE
minor Documentation issue

### ISSUE THREAD

**Issue by GastonMazzei** [YuMan-Tam/deep-hedging-demo#5]
Hey, in the 'README.md' file you have written:

`Run python ./pyqt/main.py. Check ./requirements.txt for main dependencies.`

Nevertheless there  is a '5' currently missing and a "." should be removed, the correct line being:

`Run python **./pyqt5/main.py** Check ./requirements.txt for main dependencies.`

Thanks

**Comment by YuMan-Tam** [comment]
Thank you for the correction! I fixed it.
